
name: cloneImage

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

env:
  NAME: "env_name"
  #env_var: ${{ vars.ENV_CONTEXT_VAR }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Pull images
        run: |
          for item in $(cat images)
          do
            echo "正在拉取 $item 镜像"
            docker pull $item
            if [ $? -ne 0 ];then
              echo "镜像 $item 拉取失败，将不会推送到你的私人仓库"
              echo $item |sed "s#\/#\\\\\\\/#"|xargs -L1 bash -c 'sed -i "/$0/d" images'
            fi
          done

      - name: Change image name and push
        run: |
          echo ${{ secrets.HUB_PWD }} | docker login ${{ vars.REGISTRY }} -u ${{ vars.HUB_USER }} --password-stdin
          for item in $(cat images)
          do
            export ImageName=$(echo $item | awk -F / '{print $NF}')
            echo "image_name1:$IM,2${IM},ImageName:${ImageName}"
            echo "准备推送 $item 镜像"
            export NewImageName=${{ vars.REGISTRY }}/${{ vars.NAMESPACE }}/$ImageName
            docker  tag  $item    $NewImageName
            docker push $NewImageName
            if [ $? -ne 0 ];then
              echo "镜像 $NewImageName 推送失败"
              echo $item |sed "s#\/#\\\\\\\/#"|xargs -L1 bash -c 'sed -i "/$0/d" images'
            fi
          done

