
# This is a basic workflow to help you get started with Actions

name: cloneImage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
env:
  NAME: "env_name"
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Log level: $FOO"
          echo "Tags: ${{ FOO }}"
          echo "Environment: $ENVIRONMENT"
          #docker info
          #npm -v
          pwd
          ls -al
        env:
          #LEVEL: ${{ inputs.logLevel }}
          #TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
          
